version: '3.7'
services:
  app:
    build: .
    image: net-core-angular:dev
    container_name: net-core-angular
    ports:
      - 8456:80

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Password1!"
      ACCEPT_EULA: "Y"
    container_name: net-core-angular-sql
    ports:
      - 8600:1433
